### ISSUE TITLE
Create TypeScript + Intern 4 example 

### ISSUE THREAD

**Issue by morrinene** [theintern/intern-examples#49]
Create a starter TypeScript + Intern 4 example (unit and functional tests)

- Similar to the Intern 4 tutorial, but much lighter
- Simpler examples using straight Intern.

**Comment by jason0x43** [comment]
An example for a simple TypeScript app was added in https://github.com/theintern/intern-examples/commit/09b5478ebda8bbe429bbc30d92ef952ecfc5c902. This is based on the TodoMVC framework, but all the app code has been rewritten in modular TS rather than global JS. It doesn't use webpack or any complex tooling, just TS to build modules and SystemJS to load them.
